#[cfg(feature = "cuda")]
use std::sync::atomic::Ordering;

use clap::Args;
use ort::session::Session;

use crate::config::ORT_INTRA_THREADS;
use crate::constants::FEATURE_DIM as FDIM;
#[cfg(feature = "cuda")]
use crate::pipeline::{InferenceBackend, OrtBackend};

#[cfg(feature = "cuda")]
use crate::cuda::memory::{alloc_pinned, free_pinned};

#[derive(Args, Clone)]
pub struct VerifyArgs {
    /// Path to the ONNX model file.
    #[arg(short, long)]
    pub model: String,

    /// Number of vectors to submit in the verification batch.
    #[arg(short = 'n', long, default_value_t = 4)]
    pub batch: usize,

    /// Validate exact outputs for the model generated by `scripts/generate_verify_model.py`.
    #[arg(long)]
    pub validate_generated_model: bool,

    /// Use the CUDA execution provider and direct pinned-memory `RunAsync` path.
    #[arg(long, default_value_t = true, conflicts_with = "cpu")]
    pub cuda: bool,

    /// Use the default CPU execution provider for verification.
    #[arg(long)]
    pub cpu: bool,
}

fn generated_model_input_value(batch_idx: usize, feature_idx: usize) -> f32 {
    (batch_idx as f32 + 1.0) * 10.0 + feature_idx as f32 + 1.0
}

fn generated_model_expected(batch_idx: usize) -> f32 {
    (0..FDIM)
        .map(|feature_idx| {
            generated_model_input_value(batch_idx, feature_idx) * (feature_idx as f32 + 1.0)
        })
        .sum()
}

pub fn run(args: VerifyArgs) {
    eprintln!("disrust verify: args parsed");
    let use_cuda = if args.cpu { false } else { args.cuda };

    #[cfg(not(feature = "cuda"))]
    let use_cuda = {
        if use_cuda {
            eprintln!("disrust verify: cuda feature not compiled in, falling back to cpu");
        }
        false
    };

    #[cfg(feature = "cuda")]
    if use_cuda {
        crate::cuda::preflight::verify_cuda_startup().unwrap_or_else(|e| {
            eprintln!("disrust verify preflight failed: {e}");
            std::process::exit(1);
        });
        eprintln!("disrust verify: CUDA driver preflight ok");
    } else {
        eprintln!("disrust verify: CPU mode selected");
    }

    #[cfg(not(feature = "cuda"))]
    eprintln!("disrust verify: CPU mode selected");

    let model_bytes = std::fs::read(&args.model).unwrap_or_else(|e| {
        eprintln!("Failed to read model '{}': {e}", args.model);
        std::process::exit(1);
    });
    eprintln!("disrust verify: model loaded ({} bytes)", model_bytes.len());

    if !use_cuda {
        run_cpu_verify(&model_bytes, &args);
    } else {
        #[cfg(feature = "cuda")]
        run_cuda_verify(&model_bytes, &args);
    }
}

fn run_cpu_verify(model_bytes: &[u8], args: &VerifyArgs) {
    let builder = Session::builder().unwrap_or_else(|e| {
        eprintln!("Session::builder failed: {e}");
        std::process::exit(1)
    });
    let mut builder = builder
        .with_intra_threads(ORT_INTRA_THREADS)
        .unwrap_or_else(|e| {
            eprintln!("with_intra_threads failed: {e}");
            std::process::exit(1)
        });
    let mut session = builder.commit_from_memory(model_bytes).unwrap_or_else(|e| {
        eprintln!("commit_from_memory failed: {e}");
        std::process::exit(1)
    });

    let input = if args.validate_generated_model {
        let mut values = Vec::with_capacity(args.batch * FDIM);
        for batch_idx in 0..args.batch {
            for feature_idx in 0..FDIM {
                values.push(generated_model_input_value(batch_idx, feature_idx));
            }
        }
        values
    } else {
        vec![1.0f32; args.batch * FDIM]
    };
    let input =
        ort::value::Tensor::<f32>::from_array(([args.batch, FDIM], input)).unwrap_or_else(|e| {
            eprintln!("Tensor::from_array failed: {e}");
            std::process::exit(1)
        });
    let output_name = session.outputs()[0].name().to_string();
    let outputs = session.run(ort::inputs![input]).unwrap_or_else(|e| {
        eprintln!("session.run failed: {e}");
        std::process::exit(1)
    });
    let output = outputs.get("output").unwrap_or(&outputs[0]);
    let (_shape, values) = output.try_extract_tensor::<f32>().unwrap_or_else(|e| {
        eprintln!("output extraction failed: {e}");
        std::process::exit(1)
    });

    println!(
        "disrust verify ok: mode=cpu, batch={}, output_name={}, values={}",
        args.batch,
        output_name,
        values.len()
    );
    if !values.is_empty() {
        println!(
            "output sample: first={:.6}, last={:.6}",
            values[0],
            values[values.len() - 1]
        );
    }
    validate_generated_model_if_requested(values, args.validate_generated_model);
}

#[cfg(feature = "cuda")]
fn run_cuda_verify(model_bytes: &[u8], args: &VerifyArgs) {
    let input_elems = args.batch * FDIM;
    let mut backend = OrtBackend::new_with_capacity(model_bytes, args.batch);
    let output_name = backend.output_name().to_string();

    let input_ptr = alloc_pinned(input_elems * std::mem::size_of::<f32>()).unwrap_or_else(|e| {
        eprintln!("{e}");
        std::process::exit(1);
    }) as *mut f32;
    unsafe {
        for batch_idx in 0..args.batch {
            for feature_idx in 0..FDIM {
                let offset = batch_idx * FDIM + feature_idx;
                *input_ptr.add(offset) = if args.validate_generated_model {
                    generated_model_input_value(batch_idx, feature_idx)
                } else {
                    1.0
                };
            }
        }
    }

    if !backend.try_acquire() {
        eprintln!("fresh OrtBackend was unexpectedly unavailable");
        std::process::exit(1);
    }

    let batch = backend.submit_batch(input_ptr, args.batch);
    batch.completion.wait();

    let output = unsafe { std::slice::from_raw_parts(batch.output_ptr, batch.output_len) };
    println!(
        "disrust verify ok: batch={}, output_name={}, values={}",
        args.batch,
        output_name,
        output.len()
    );
    if !output.is_empty() {
        println!(
            "output sample: first={:.6}, last={:.6}",
            output[0],
            output[output.len() - 1]
        );
    }
    validate_generated_model_if_requested(output, args.validate_generated_model);

    batch.session_available.store(true, Ordering::Release);
    drop(batch);
    unsafe { free_pinned(input_ptr.cast()) }.unwrap_or_else(|e| {
        eprintln!("{e}");
        std::process::exit(1);
    });
}

fn validate_generated_model_if_requested(values: &[f32], validate: bool) {
    if !validate {
        return;
    }

    for (batch_idx, &actual) in values.iter().enumerate() {
        let expected = generated_model_expected(batch_idx);
        let diff = (actual - expected).abs();
        if diff > 1e-4 {
            eprintln!(
                "generated-model validation failed at row {}: expected {:.6}, got {:.6}",
                batch_idx, expected, actual
            );
            std::process::exit(1);
        }
    }
    println!("generated-model validation ok");
}
